services:
  mysql:
    image: mysql:8.0
    container_name: track-mysql

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: track-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: track-app
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data: