services:
  mysql:
    image: mysql:8.0
    container_name: track-mysql

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    # MySQL이 실제로 접속 가능한 상태인지 Docker가 반복해서 검사
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  redis:
    image: redis:7-alpine
    container_name: track-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: track-app
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql-data: