spring:
  profiles:
    include: secret
  application:
    name: track
  datasource:
    url: jdbc:mysql://localhost:3307/${database-name}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 2s

jwt:
  secret: ${jwt-secret}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000