# `application-secret.example.yml`을 복사하여 `application-secret.yml`을 생성한 뒤 자신의 환경에 맞게 값을 입력하세요.

DATABASE_NAME: your_database_name
DATABASE_USERNAME: your_database_username
DATABASE_PASSWORD: your_database_password
JWT_SECRET: your_jwt_secret
MAIL_USERNAME: email
MAIL_PASSWORD: email_app_password