apiVersion: apps/v1
kind: Deployment

metadata:
  name: track-app
  namespace: track

spec:
  replicas: 1     # Spring Boot Pod을 하나로 유지

  selector:
    matchLabels:
      app: track-app    # Deployment가 자신이 관리할 Pod를 app: track-app 라벨로 찾음

  template:
    metadata:
      labels:
        app: track-app

    spec:
      containers:
        - name: track-app
          image: ghcr.io/cherrynniii-track/track-backend:latest   # GHCR에 저장된 도커 이미지 실행
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: JWT_SECRET
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/$(DATABASE_NAME)"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: track-app-secret
                  key: MAIL_PASSWORD